# Welcome to Maker 52 FabLab Chaumont !
#
# Fichier de configuration de Jekyll

# +++++++++++++++ Le site +++++++++++++++++++
title: Maker 52
subtitle: FabLab Chaumont
moto: Apprendre, Faire et Partager
email: fablab[at]maker52[point]fr
description: >- # this means to ignore newlines until "baseurl:"
  "Apprendre, Faire et Partager."
baseurl: "" # the subpath of your site, e.g. /blog
url: "maker52.fr" # the base hostname & protocol for your site, e.g. http://example.com

logo: "/assets/maker-52-viaduc-chaumont-impression-3d-600x424.jpg"

lang: fr
timezone: Europe/Paris # +1 / DST +2

twitter_username:
github_username:  FabLab-Chaumont-52
google_analytics: UA-154263807-2

# +++++++++++++++++ Architecture de l'information ++++++++++++++++

# valeur par défaut
defaults:
  # _posts
  - scope:
      type: posts
    values:
      layout: post

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page


# +++++++++++++++++ Configuration de jekyll +++++++++++++++++

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


# force Jekyll processing on dotted file name (eg: .htaccess)
# and underscored folder names (eg : _pages)
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true
  parse_span_html: true
