# Welcome to Maker 52 FabLab Chaumont !
#
# Fichier de configuration de Jekyll

# +++++++++++++++ Le site +++++++++++++++++++
title: Maker 52 - FabLab Chaumont
subtitle:
moto: Apprendre, Faire et Partager
email: fablab[at]maker52[point]fr
email_covid: covid@maker52.fr
description: Laboratoire de Fabrication, où n'importe qui peut fabriquer presque n'importe quoi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maker52.fr" # the base hostname & protocol for your site, e.g. http://example.com

logo: "/img/logo/logo-maker-52-v2-optim.svg"

lang: fr
timezone: Europe/Paris # +1 / DST +2

twitter_username:
github_username:  FabLab-Chaumont-52
google_analytics: UA-154263807-2

# +++++++++++++++++ Architecture de l'information ++++++++++++++++

collections_dir: collections

collections:
  projets:
    output: true
  docs:
    output: true
  machines:
    output: true

# valeur par défaut
defaults:
  - scope:
      type: posts
    values:
      layout: post

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page

  - scope:
      type: projets
    values:
      layout: projet

  - scope:
      type: docs
    values:
      layout: doc


# +++++++++++++++++ Configuration de jekyll +++++++++++++++++

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


# force Jekyll processing on dotted file name (eg: .htaccess)
# and underscored folder names (eg : _pages)
include:
  - _pages
  - node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
  - node_modules/jquery/dist/jquery.slim.min.js
  - node_modules/js-cookie/src/js.cookie.js
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true
  parse_span_html: true

sass:
  load_paths:
    - _sass
    - node_modules/bootstrap/scss
